# Generated by Django 2.1.1 on 2018-09-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_sensor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='value',
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_id',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
