# Generated by Django 2.1.1 on 2018-09-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_datapoint_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoint',
            name='owner',
        ),
        migrations.AddField(
            model_name='datapoint',
            name='sensor',
            field=models.CharField(default='no associated sensor', max_length=200),
        ),
        migrations.AddField(
            model_name='sensor',
            name='owner',
            field=models.CharField(default='no owner', max_length=200),
        ),
    ]
