# Generated by Django 2.1.1 on 2018-09-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20180917_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoint',
            name='sensor',
        ),
        migrations.AddField(
            model_name='sensor',
            name='mylist',
            field=models.ManyToManyField(to='monitor.DataPoint'),
        ),
    ]
