# Generated by Django 2.1 on 2018-09-19 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_auto_20180919_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='sensor_id',
        ),
        migrations.AddField(
            model_name='sensor',
            name='api_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='sensor',
            name='name',
            field=models.CharField(default='n/a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='unit',
            field=models.CharField(default='°C', max_length=10),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
