# Generated by Django 2.1 on 2018-09-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_auto_20180919_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='malfunction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensor',
            name='max_value',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='min_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
